### PR TITLE
#607 Use safe areas for image preview

### LINKED ISSUE #607: [BUG] <title>
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When viewing a longer image in the media viewer, the default zoom level extends the image beyond the safe areas. This cuts off at the top and bottom information. Note the "primary" text in the image getting covered by the notch. Test post: https://mastodon.online/@samhenrigold/109315656668714919
PXL_20221110_135403010
PXL_20221110_135412158

### Expected Behavior

The 100% zoom level should just fill the safe area, not the entire display.

### Steps To Reproduce

_No response_

### Environment

```markdown
- Device: iPhone 14 Pro
- OS: iOS 16.2 (20C5043e)
- Version: v1.4.7
- Build: 182
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by painhapp**
fixes #607 

| before | after |
|--------|------|
|  Screenshot 2022-11-18 at 3 52 37 | Screenshot 2022-11-18 at 3 55 10 |

### CODE REVIEW

**Comment by painhapp** [comment]
Sure, will look into that tmr 👍🏼

**Comment by painhapp** [comment]
@j-f1 thanks for pointing that out. fixed - please check again

**Comment by j-f1** [comment]
Thanks! That’s definitely better. One other small issue I noticed is that when manually swiping away the image, it jumps to the right at the start of the drag gesture and then otherwise follows my finger. I don’t remember this happening before.

**Review by zeitschlag — APPROVED** [review]

**Comment by zeitschlag** [comment]
@painhapp Hey, thank you for your work 🥳🥳👍

**Pull request merged**
