### PR TITLE
Support japanese

### PR DESCRIPTION
**Pull request by hirossan4049**
Add japanese.

### CODE REVIEW

**Comment by MainasuK** [comment]
We are preparing the Crowdin project for localization. Once it finish, I will be back here.

**Comment by MainasuK** [comment]
The [Crowdin](https://crowdin.com/project/mastodon-for-ios) is prepared and I will get some other things done then merge this PR later. 
Thank you for your contribution.

**Comment by smorimoto** [comment]
OK - I just rebased on the latest develop channel to get rid of unnecessary commits.

**Comment by smorimoto** [comment]
Some translations seem a little unnatural and/or inconsistent. Is this ready for review? If it's under construction, we can wait for that.

**Comment by MainasuK** [comment]
> Some translations seem a little unnatural and/or inconsistent. Is this ready for review? If it's under construction, we can wait for that.

I can handle the codes. Please use Crowdin to localize directly. 😃

**Comment by hirossan4049** [comment]
Fixed unnatural and inconsistent translations.
Please review.

**Comment by MainasuK** [comment]
Please let me clarify. The localization template is two JSON files under the `/Localization`. And that is already synced with Crowdin. Please directly review and contribute [here](https://crowdin.com/project/mastodon-for-ios).

Once @smorimoto thinks it is ready for publishing. I'll generate the strings again.

Thanks.

**Pull request merged**
