### PR TITLE
Improve accessibility of the thread screen

### PR DESCRIPTION
**Pull request by j-f1**
- combine the avatar, display name, username, timestamp, menu, and eye button into a single accessibility element
- set an appropriate label for that element that includes the relevant information
- attach custom accessibility actions for the actions formerly in the “…” menu
- attach an enable/disable content warning when the corresponding button is visible
- improve labelling of the reblog & favorite buttons
- remove the status metric view from the accessibility hierarchy
  - read the full date after the relative timestamp in the author view
  - add “show reblogs” and “show favorites” as custom actions on the reblog & favorite buttons

I moved the author section into its own subview so the accessibility properties can be directly controlled. Let me know if I should undo some of the changes I made to move code into that subview :)

### CODE REVIEW

**Comment by j-f1** [comment]
One issue I’m seeing (and I’d guess that it’s the underlying cause of #328) is that I’m unable to go past the “Post from [name]” header of a thread in VoiceOver, but tapping on the header seemingly takes me to a identical-sounding but different title that I can navigate past. Covering it up for now by navigating to the table view directly when showing the thread, but if you cancel a reply you’ll still end up in the bad state.

**Comment by j-f1** [comment]
Should this one also be retargeted to `develop`?

**Comment by MainasuK** [comment]
> Should this one also be retargeted to `develop`?
Yes. We use git-flow and you can check [this](https://github.com/mastodon/mastodon-ios/blob/main/Documentation/CONTRIBUTING.md). 


> One issue I’m seeing (and I’d guess that it’s the underlying cause of https://github.com/mastodon/mastodon-ios/issues/328) is that I’m unable…

I need more context to understand that problem. The app currently read the whold post in the home timeline. The reactions (reply, repost, like…) only available after tap to enter the detail page. This behaivor is some mimics from Twitter app. (I wonder waht is the best practical)

- The cell configuration using `Core Data` entity's publisher to bind the property to UI. That's maybe not fit the Voice-Over to get the correct value.
- There is a VoiceOver menu or something missing for reactions.

**Comment by MainasuK** [comment]
> Covering it up for now by navigating to the table view directly when showing the thread, but if you cancel a reply you’ll still end up in the bad state.

I have to admit the lack of knowledge about VoiceOver. And this changes should make sense.

**Comment by MainasuK** [comment]
The code conflict is due to the new menu entry for bookmarks. That's too late and I'll handle this tomorrow.

Also, thank you for your contributions.

**Comment by j-f1** [comment]
> I need more context to understand that problem. The app currently read the whold post in the home timeline. The reactions (reply, repost, like…) only available after tap to enter the detail page. This behaivor is some mimics from Twitter app. (I wonder waht is the best practical)

The issue here is that when you tap on a post in the timeline you're taken to the detail view as expected but your cursor starts off on the title in the navigation bar, and there's no way to navigate to the post actions for some reason. This might well be a bug in iOS since I am struggling to identify the conflicting element using Accessibility Inspector.

**Comment by MainasuK** [comment]
LGTM. Thank you for your works.

**Pull request merged**
