### PR TITLE
[Server picker] Tuned Dynamic Type support for the next/back buttons

### PR DESCRIPTION
**Pull request by jverkoey**
Note: this is a **stacked pull request** on top of https://github.com/mastodon/mastodon-ios/pull/572. It should not be merged until https://github.com/mastodon/mastodon-ios/pull/572 has been submitted.

Part of https://github.com/mastodon/mastodon-ios/issues/191

This change includes the following considerations / changes:

- The back button now fits-to-size and has a minimum width of 100 points. Prior to this change, the back button would take up 1/3 of the screen's width. The constant `100` was chosen semi-arbitrarily to be a reasonable minimum tap area width.
- Both the back and next buttons now respond to Dynamic Type settings changes.
- Both buttons now have non-zero contentEdgeInsets in alignment with the padding values added in https://github.com/mastodon/mastodon-ios/pull/572

| Dynamic Type | Before | After |
|:----|:----:|:---:|
| **AX5**: buttons are taller | The Mastodon server picker screen in AX5 mode. The button titles have very little padding | The Mastodon welcome screen in AX5 mode. The buttons are slightly larger, affording more space for the button titles |
| **AX5** (German): titles no longer clip | The Mastodon server picker screen in German AX5 mode. The button titles are clipped | The Mastodon welcome screen in German AX5 mode. The button titles are no longer clipped |
| **Large**: back button is narrower | The Mastodon server picker screen at the default size | The Mastodon server picker screen in the default size. The back button is slightly narrower |

### CODE REVIEW

**Comment by Yonodactyl** [comment]
Are there any concerns about sizing constraints not properly adapting to localized strings?

**Comment by jverkoey** [comment]
Added German screenshots. Looks like the prior behavior was causing button titles to clip, and that's now fixed.

**Comment by Yonodactyl** [comment]
Well that is awesome. Really glad to see these improvements

**Review by kimar — APPROVED** [review]
@jverkoey thanks a bunch! Could you please resolve the conflicts? Then I'm happy to merge this PR.

**Pull request merged**
