### PR TITLE
Add an alternate app icon for debug builds

### PR DESCRIPTION
**Pull request by j-f1**
This makes it easier to tell the debug and production apps apart. I did a basic hue rotation and am totally open to different colors or some other alteration, I just don’t want to have to wonder which app I’m using.

IMG_7862

Icon created using…

```sh
find *.png -exec magick \{\} -modulate 100,100,185 ../AppIcon-Debug.appiconset/\{\} \; 
```

### CODE REVIEW

**Comment by Suzie97** [comment]
image

I made this icon and i think this one will be a better icon for the debug version. I can provide the required files if needed.

**Comment by j-f1** [comment]
Ooh I like that one a lot better!

**Comment by Gargron** [comment]
That looks pretty cool, thanks!

**Comment by MainasuK** [comment]
https://github.com/mastodon/mastodon-ios/issues/339

Ohhh.
Maybe we really need to add the custom App Icon features.
So users could choose their favorite one. @Gargron 

What I need is a design about the setting entry and how to display icons.  

P.S.
And the app needs the opaque (no alpha) png or jpeg icon image in 1024 x 1024.

**Comment by j-f1** [comment]
Closing this for now since the changes I made were fairly simple and I’m no longer blocked (I just keep a third-party app around for notification purposes)

**Pull request closed without merging**
