### PR TITLE
Fix calculating the position of the keyboard in ComposeContentViewController

### LINKED ISSUE #890: [BUG][iPadOS] Accessibility Bug - Alt text for image description not visible and cannot be entered
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using iOS Mastodon app on an iPad, enter an image, the entire image usually cannot be seen.   A string overlaying the bottom of the image must be selected so that text can be entered to describe the image for accessibility.   However, the string is often not visible because not all of the image can be seen.  If you scroll to the bottom to see the string, when you release your finger, the image bounces back,  so the bottom of the image is not seen again. (Added later: this happens if the virtual keyboard is large size, even if not shown because physical keyboard is present)

There is no way  to scroll to see the alt text overlay and select it to give it focus and to type at the same time.   Being able to enter alt text  is essential for providing auditory content used by people with low vision.  

Here is a recent discussion of this bug on a leading Mastodon art source 
.  https://fosstodon.org/@photonstopper@mastodon.art/109699888660622737 

There are other issues describing this bug, but they are not listed as bugs and have not been assigned to someone in the project.  #864 and #813 Marking one of those as a bug and assigning it would be enough to close this.  I'm concerned that it isn't getting project attention because it may not be clear enough that this is a serious accessibility bug.

Workaround: if you add an additional image at the bottom that you will delete before posting, then you can see and edit the overlay for adding alt text to the images above that last image.  then you can delete the last dummy image.  Or make the virtual keyboard small (but the small keyboard is a problem for people with limited vision).

### Expected Behavior

Expect to be able to see the field in which to enter the alt text description and to be able to type into it.  This works on the "official" Android Mastodon app and on the Web app, but not on the iPadOS app.

### Steps To Reproduce

1. On an iPad, insert an image in a toot
2. Observe that you cannot see the input line at the bottom of the image, because it is below the part of the image displayed.  
3. Scroll using touch to see the bottom of the image so you can see the text suggesting to enter a description
4. Observe that when you stop scrolling and lift finger, it scrolls back so can't see where the "alt" text must be entered, so cannot enter the "alt" text for accessibility.

### Environment

```markdown
- Device: iPadAir 4th generation
- OS: iPadOS
- Version: 16.2
- Build: 20C65
```

### Anything else?

No

### LINKED ISSUE #946: [BUG] [iPadOS] Cannot scroll to bottom of composition box
While replying in a thread on iPadOS, I am unable to scroll to the bottom of the composition box to see what I am typing.

Using the TestFlight version of the app, v1.4.12 (268)

https://user-images.githubusercontent.com/576958/219967863-c96670c2-3511-4067-bd9b-616bc08ca782.MOV

### PR DESCRIPTION
**Pull request by j-f1**
Fixes #890. Fixes #946.

### CODE REVIEW

**Comment by j-f1** [comment]
Actually, this is the wrong approach. Instead, code using `KeyboardResponderService` should be [updated to use the keyboard layout guide](https://developer.apple.com/documentation/uikit/keyboards_and_input/adjusting_your_layout_with_keyboard_layout_guide) (but merging this PR will still significantly improve the UX in the meantime until that change can be made)

**Comment by wayneca** [comment]
The other changes to alt handling that went out in the update yesterday did not fix #890 on iPads.   

 Question to the people who authorize updates to the code: when will this fix get approved?

**Comment by davmillar** [comment]
> Actually, this is the wrong approach. Instead, code using `KeyboardResponderService` should be [updated to use the keyboard layout guide](https://developer.apple.com/documentation/uikit/keyboards_and_input/adjusting_your_layout_with_keyboard_layout_guide) (but merging this PR will still significantly improve the UX in the meantime until that change can be made)

Hiya, just wondering if you mean that this fix is likely to merge soon or if you're merely speculating that this would be an improvement if merged. It's still a very frustrating problem that I run into multiple times daily to the point where I'd offer a cash bug bounty if there weren't already this seemingly-viable fix pending. Thanks!

**Comment by j-f1** [comment]
I hope the maintainers will merge this PR soon! That was intended to track a future refactor that could improve keyboard performance further, maybe I should have been more clear about that.

**Comment by wayneca** [comment]
I'm searching for who works on accessibility in Mastodon to let them know about this.  Is there a list of people who approve changes for this code?

**Comment by wayneca** [comment]
I contacted someone who was assigned and reviewed a change to that file a couple of months ago.

**Comment by kimar** [comment]
LGTM @j-f1 just tested this and it looks fine to me.

@wayneca thank you very much for sticking on this issue and pinging me!

**Review by kimar — APPROVED** [review]

**Comment by wayneca** [comment]
@kimar @j-f1  thanks for fixing this!

**Pull request merged**
