### PR TITLE
Add support for saving and loading draft posts

### LINKED ISSUE #482: [FEATURE] Canceled Toot possible saved as Draft
If a toot is not completed and you cancel it, you should be asked whether you want to save it as a draft (for later) or not.

### LINKED ISSUE #846: Toot lost in poor network conditions
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I composed a toot in the app while on a slow/congested mobile network, spending a fair amount of time as usual checking spelling and wording choice. Then I hit publish, or actually “Publicera” as I’m using the app in Swedish.

I think it was about the same time that I hit publish that I lost data traffic entirely, at least I saw no “bars” right after.

The new toot UI closed but my toot wasn’t published. I don’t recall seeing a error or anything unusual.

### Expected Behavior

If it’s not possible to publish the toot due to network conditions I’d expect the UI to remain open and show some kind of error, so that I can try again later.

If there was an auto-saving drafts feature I’d additionally expect my toot to remain in drafts if I closed the app right after publishing and didn’t notice it didn’t go through.

### Steps To Reproduce

I can’t give reliable steps to reproduce because I can’t control the network around me and am still on the bad network. If at home on WiFi what I’d try is turning off power to the WiFi router and immediately after hit publish, before the phone shows that the network connection has been lost.

If there is no code that tries to handle network issues when posting today then I trust this report is enough to track that. But if there is some code and it should actually work then I’m happy to try reproducing the problem.

### Environment

```markdown
- Device: iPhone 12
- OS: iOS 16.1.1
- Version: v1.4.9
- Build: 224
```

### Anything else?

I toot at https://mastodon.nu/@foolip

### PR DESCRIPTION
**Pull request by j-f1**
Fixes #482

- Add a new `Draft` entity that represents an unfinished post. It is similar to a `Status` but doesn’t have a snowflake ID, and the attachments are represented differently.
- When cancelling the compose view controller, the action sheet now allows you to save a draft.
- When starting a publish action, a draft is automatically saved. (should fix #846)
- When the publish succeeds (or the user taps “discard” in the action sheet), the saved draft will be deleted.
- drafts store a copy of their media locally so that it can be re-uploaded if needed (since Mastodon by default deletes media not attached to a published post after 1 day)
- media is mostly restored when restoring a draft. (question: why does the code try to access a security scoped bookmark here? trying to figure out how to get this to fully work)
- currently, multiple drafts are supported per user, but one will be selected “at random” (`Set/firstObject`) when the compose button is tapped
- currently there is no way to compose a new post if you have a draft, the draft will always appear.

Also:
- refactors to make storing drafts easier:
  - unify the 2 visibility enums used in the app (`MastodonVisibility` + `Mastodon.Entity.Status.Visibility`)
  - refactor how poll expirations are stored
    - also updates to use the system date formatting logic instead of custom localized strings for each duration option
    - adds a 12 hour poll duration (https://github.com/mastodon/mastodon/pull/21131)
- clean up some dead code

TODO: 
- [x] fix #846 by auto-saving a draft when tapping “publish”
- [x] figure out what to do if `output` is nil when saving a draft
- [ ] auto-save at intervals (/ when going to the background?)
- [ ] UI polish?
- [ ] handle multiple drafts? / add UI for drafts?

### CODE REVIEW

**Comment by j-f1** [comment]
Ok, I think this is ready for a first pass. The only UI change is the addition of the “Save Draft” button in the action sheet, and future work to improve the experience should mostly be in the UI department.

**Comment by j-f1** [comment]
@kimar / @zeitschlag Is there interest in merging this? I’m happy to fix the merge conflicts but I don’t want to do that if it’s likely that the PR will sit for months again and get even more merge conflicts.

**Comment by testuser51** [comment]
Please add this. Sometimes the problem is not the internet, but the server is down. I was thinking of deleting mastodon because I lost my posts several times

**Comment by movalex** [comment]
Hey, such a nice feature, it's a shame it is still not merged. Please @j-f1, delete those unrelated todos in description, about UI polish and other non-essential tweaks. Hopefully this will push devs to accept it faster.

**Comment by j-f1** [comment]
Unfortunately there is a significant amount of work needed to integrate this functionality with the post editing functionality which is very similar in terms of implementation. I do not want to put that effort in unless I am confident it will be merged. It would be about as difficult as starting over again.

**Comment by j-f1** [comment]
Given those facts, I’m closing this — the code may be useful as a reference but any further work should start over from a new PR.

**Comment by StephanEggermont** [comment]
Local storage first is essential. The application can not work otherwise. The auto-saving also needs to happen when the app is swapped out

**Comment by StephanEggermont** [comment]
Still needed

**Pull request closed without merging**
