### PR TITLE
Updated Welcome-Screen (IOS-134)

### PR DESCRIPTION
**Pull request by zeitschlag**
This PR updates the Welcome-Screen.

- It removes the fancy swipable education-pages (R.I.P! You'll always be remembered!) and replaces the content with a simpler sheet with some explanations.
- There's also a new button to directly sign up for an account on `mastodon.social`

Edit: [My first approach](https://github.com/mastodon/mastodon-ios/tree/134-new-welcome-screen-old) was to use the original implementaion that didn't use AutoLayout, but when I went to bed yesterday, I thought: Why? So I changed it (again).

### CODE REVIEW

**Comment by ThatOneCalculator** [comment]
This PR was not reviewed thoroughly, as Mastodon is a decentralized way to access the Fediverse, so pushing a specific server is not beneficial for the network.

**Comment by yosoyfreeman** [comment]
I think the new bottom to sing up directly on Mastodon.Social may result in people having a harder time to understand the benefits of a decentralized network and may be detrimental to smaller communities.

**Comment by ExperiencersInternational** [comment]
@ThatOneCalculator 100% agree, but I think the main reasoning for this was a better overall user experience

Why they can't just implement like a server selector feature using domains on joinmastodon.org idk

**Comment by JeffAlyanak** [comment]
> @ThatOneCalculator 100% agree, but I think the main reasoning for this was a better overall user experience

I agree that it's important to lower the friction of onboarding, but pointing people towards a specific singular server is going to be bad for this long-term.

> Why they can't just implement like a server selector feature using domains on joinmastodon.org idk

I think the Join Mastodon landing page does a much better job of balancing onboarding and long-term network health. It provides a concise explanation and a list of servers to join.


Ideally, I'd love to see a simple way for server operators to override this with a list of servers of their own, so that friendly, like-minded servers can point prospective users to one another.

**Pull request merged**
